### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by gserpep** [SaraBabakN/MFCL-NeurIPS23#2]
Hello,

I have been trying to reproduce the experiments following the instructions reported in the repo. There were some easily fixable errors (mainly related to missing variables or setting the CUDA device to variables/models). However, now, I encounter the following one.

```
/opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "./projects/MFCL-NeurIPS23/main.py", line 73, in <module>
    user.train(model, lr, teacher, generator, counter)
  File "./projects/MFCL-NeurIPS23/clients/MFCL.py", line 37, in train
    self.train_cl(model, teacher, opt)
  File "./projects/MFCL-NeurIPS23/clients/MFCL.py", line 58, in train_cl
    loss_kd = self.kd(x_com, previous_linear, logits_pen, previous_teacher)
  File "./projects/MFCL-NeurIPS23/clients/MFCL.py", line 66, in kd
    dw_KD = self.dw_k[-1 * torch.ones(len(kd_index),).long()].to(self.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

The error is raised when the first task ends and the second one starts. Could you please help me fix the problem?

Thanks a lot,
Giuseppe

**Comment by smart0eddie** [comment]
may you post the cuda error message?
I also encounter such problem at similar place

the cuda complains that
 Assertion `t >= 0 && t < n_classes` failed.

I think it might be caused by the ce loss
the network classification output has only 10 dimension while the second task requires classifying 20 classes

**Comment by gserpep** [comment]
The first row of the code block in my previous comment reports the message error (the same one you are encountering). For clarity, here is the shortened message:

`nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion t >= 0 && t < n_classes failed.`

 I also believe the error is related to a mismatch in the dimensions when moving from the first task to the second one.

**Comment by SaraBabakN** [comment]
Thank you for raising this problem. The last line in the main.py misses the step where the model's output layer gets updated for the next task. I think I fixed the problem, along with other minor bugs. Please let me know if the problem still exists on your side.

**Comment by smart0eddie** [comment]
Thank you for your response.
The updated code works fine on CIFAR 100.
The accuracy is about 5% lower than that reported in the paper
The following is the program output.

round 9, accuracy: 27.600000381469727
round 19, accuracy: 38.20000076293945
round 29, accuracy: 51.099998474121094
round 39, accuracy: 55.400001525878906
round 49, accuracy: 61.0
round 59, accuracy: 65.19999694824219
round 69, accuracy: 63.0
round 79, accuracy: 67.5999984741211
round 89, accuracy: 68.30000305175781
round 99, accuracy: 69.5
round 109, accuracy: 39.099998474121094
round 119, accuracy: 40.099998474121094
round 129, accuracy: 45.099998474121094
round 139, accuracy: 45.95000076293945
round 149, accuracy: 48.70000076293945
round 159, accuracy: 48.349998474121094
round 169, accuracy: 49.25
round 179, accuracy: 49.900001525878906
round 189, accuracy: 50.150001525878906
round 199, accuracy: 50.599998474121094
total_accuracy_1: [tensor(48.), tensor(53.2000)]
round 209, accuracy: 39.46666717529297
round 219, accuracy: 40.79999923706055
round 229, accuracy: 42.16666793823242
round 239, accuracy: 43.16666793823242
round 249, accuracy: 43.86666488647461
round 259, accuracy: 44.46666717529297
round 269, accuracy: 44.46666717529297
round 279, accuracy: 44.93333435058594
round 289, accuracy: 45.099998474121094
round 299, accuracy: 44.900001525878906
total_accuracy_2: [tensor(43.5000), tensor(33.), tensor(58.2000)]
round 309, accuracy: 35.0
round 319, accuracy: 36.70000076293945
round 329, accuracy: 37.724998474121094
round 339, accuracy: 38.32500076293945
round 349, accuracy: 39.29999923706055
round 359, accuracy: 39.20000076293945
round 369, accuracy: 39.57500076293945
round 379, accuracy: 40.099998474121094
round 389, accuracy: 40.224998474121094
round 399, accuracy: 40.5
total_accuracy_3: [tensor(43.4000), tensor(21.1000), tensor(40.6000), tensor(56.9000)]
round 409, accuracy: 34.63999938964844
round 419, accuracy: 36.5
round 429, accuracy: 36.380001068115234
round 439, accuracy: 36.97999954223633
round 449, accuracy: 36.84000015258789
round 459, accuracy: 37.13999938964844
round 469, accuracy: 37.279998779296875
round 479, accuracy: 37.279998779296875
round 489, accuracy: 37.65999984741211
round 499, accuracy: 37.13999938964844
total_accuracy_4: [tensor(40.3000), tensor(21.2000), tensor(30.7000), tensor(35.4000), tensor(58.1000)]
round 509, accuracy: 32.03333282470703
round 519, accuracy: 33.28333282470703
round 529, accuracy: 34.45000076293945
round 539, accuracy: 34.18333435058594
round 549, accuracy: 34.516666412353516
round 559, accuracy: 34.233333587646484
round 569, accuracy: 34.63333511352539
round 579, accuracy: 34.96666717529297
round 589, accuracy: 34.43333435058594
round 599, accuracy: 34.68333435058594
total_accuracy_5: [tensor(36.8000), tensor(18.2000), tensor(28.), tensor(26.5000), tensor(39.9000), tensor(58.7000)]
round 609, accuracy: 31.885713577270508
round 619, accuracy: 32.75714111328125
round 629, accuracy: 32.5428581237793
round 639, accuracy: 32.728572845458984
round 649, accuracy: 32.9571418762207
round 659, accuracy: 32.57143020629883
round 669, accuracy: 32.78571319580078
round 679, accuracy: 33.0428581237793
round 689, accuracy: 32.78571319580078
round 699, accuracy: 32.88571548461914
total_accuracy_6: [tensor(34.9000), tensor(17.5000), tensor(23.7000), tensor(20.5000), tensor(28.6000), tensor(44.5000), tensor(60.5000)]
round 709, accuracy: 30.087499618530273
round 719, accuracy: 31.012500762939453
round 729, accuracy: 30.987499237060547
round 739, accuracy: 31.262500762939453
round 749, accuracy: 31.3125
round 759, accuracy: 31.162500381469727
round 769, accuracy: 31.112499237060547
round 779, accuracy: 30.875
round 789, accuracy: 30.700000762939453
round 799, accuracy: 30.9375
total_accuracy_7: [tensor(31.9000), tensor(15.8000), tensor(23.6000), tensor(16.9000), tensor(22.7000), tensor(38.2000), tensor(37.4000), tensor(61.)]
round 809, accuracy: 28.9777774810791
round 819, accuracy: 29.633333206176758
round 829, accuracy: 30.577777862548828
round 839, accuracy: 30.133333206176758
round 849, accuracy: 30.0
round 859, accuracy: 29.955554962158203
round 869, accuracy: 30.08888816833496
round 879, accuracy: 30.200000762939453
round 889, accuracy: 30.14444351196289
round 899, accuracy: 29.64444351196289
total_accuracy_8: [tensor(26.2000), tensor(14.4000), tensor(20.1000), tensor(14.7000), tensor(17.3000), tensor(31.6000), tensor(32.2000), tensor(48.6000), tensor(61.7000)]
round 909, accuracy: 27.90999984741211
round 919, accuracy: 27.959999084472656
round 929, accuracy: 28.299999237060547
round 939, accuracy: 28.299999237060547
round 949, accuracy: 28.079999923706055
round 959, accuracy: 27.81999969482422
round 969, accuracy: 27.670000076293945
round 979, accuracy: 27.829999923706055
round 989, accuracy: 27.790000915527344
round 999, accuracy: 27.6200008392334
total_accuracy_9: [tensor(23.6000), tensor(15.1000), tensor(20.1000), tensor(11.9000), tensor(13.), tensor(23.2000), tensor(26.2000), tensor(33.6000), tensor(44.), tensor(65.5000)]
forgetting: tensor(25.8295)

**Comment by gserpep** [comment]
Thanks a lot for your prompt fix, @SaraBabakN.

I haven't tried the new version yet. I will try it tomorrow and close the issue if everything works out.

**Comment by gserpep** [comment]
The updated version of the code is working. I am closing the issue. Thanks a lot again for taking care of it!
